### ISSUE TITLE
type of file

### ISSUE THREAD

**Issue by jawad9-11** [bcgsc/straglr#50]
can anyone tell me what should be the feature of bam file which i want to use as an input? i will be very thankful

**Comment by readmanchiu** [comment]
The bam file should use the same reference genome fasta file as the one you provide as the second parameter (`genome_fasta`) to Straglr.
Also, when you run `minimap2`, please turn on `-Y` to use soft-clipping in supplementary alignments so that the entire read sequence is accessible from the SAM record.

**Comment by jawad9-11** [comment]
Okay, Sir thank you very much for your time.

**Comment by jawad9-11** [comment]
Hi, I want to ask if you perform straglr on bam file of an individual what is the average entries in bed or tsv file.
